version: 1.0.{build}

image: Visual Studio 2019

before_build:
  - dotnet restore src/Elmish.Navigation.sln

build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true

deploy:
  provider: NuGet
  api_key:
    secure: $(NUGET_KEY)
  skip_symbols: false
  artifact: /.*(\.|\.s)nupkg/